---

name: hermesv3_bu

channels:
  - conda-forge
  - anaconda

dependencies:
  - python = 3
  - numpy
  - netcdf4 >= 1.3.1
  - python-cdo >= 1.3.6
  - geopandas
  - pyproj
  - configargparse
  - cf_units >= 1.1.3
  - pytz
  - timezonefinder
  - mpi4py
  # Testing
  - pytest
  - pytest-cov
  - pycodestyle
  - shapely
